version: “3.8”

volumes:
  postgres-data:

services:
  web:
    build: ./web
    ports:
      # - 80:80
      # - 443:443
      - 580:80
      - 3500:3000
      - 3501:3001
      - 3502:3002
    restart: always
    volumes:
      - ./web/html:/var/www/html
      - ./web/volumes/apache2:/etc/apache2
      - ./web/volumes/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./web/volumes/backup_db:/home/backup_db
      - ./web/volumes/php/8.2/apache2/php.ini:/etc/php/8.2/apache2/php.ini
    working_dir: /var/www/html
    tty: true
    # platform: linux/x86_64 m1以外はコメントアウト
    privileged: true 
    depends_on: 
      - db

  db:
    build: ./db
    ports:
      # - 5432:5432
      - 5432:5432
    restart: always
    platform: linux/x86_64
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
       - postgres-data:/var/lib/postgresql/data
    tty: true
    privileged: true 

